version: '2'
services:
    weather-app:
        image: weather
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://weather-mysql:3306/weather?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=weather-elasticsearch:9300
        ports:
            - 8080:8080
    weather-mysql:
        extends:
            file: mysql.yml
            service: weather-mysql
    weather-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: weather-elasticsearch
